version: '3.5'
services:
  # filestorage:
  #   build: ./filestorage
  #   ports:
  #     - 8000:8000

  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: afonya
      POSTGRES_DB: user_db

  backend_auth:
    build: ./user
    ports:
      - "80:8000"
    restart: always
    env_file: ./user/.env
    environment:
      - PG_DSN=postgres://postgres:afonya@db:5432/user_db
    depends_on:
      - db
