version: '3.5'
services:
  filestorage:
    build: ./filestorage
    ports:
      - 8000:8000
  backend_auth:
    build: .
    ports:
      - "80:8000"
    volumes:
      - ./storage:/app/storage/:rw
