version: '3.5'
services:
  filestorage:
    build: ./filestorage
    ports:
      - 8000:8000

  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: afonya
      POSTGRES_DB: user_db

  backend_auth:
    build: .
    ports:
      - "80:8000"
    volumes:
      - ./storage:/app/storage/:rw
